server:
  servlet:
    context-path: /sonar
  port: 8044


spring:
  application:
    name: sonar-server
  datasource:
    name: amp
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://172.30.106.138:3306/sonar?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20 
  redis:
    host: 172.30.106.138
    port: 6379 # Redis server port.
    password: 12345 # Login password of the redis server.
    flush-mode: on-save   # Sessions flush mode.
    namespace: spring:session  # Namespace for keys used to store sessions.
    database: 8
#    lettuce:
#      pool:
#        max-active: 8
#        min-idle: 1
#        max-idle: 1
#        max-wait: -1

# Mybatis配置
mybatis: 
  mapper-locations: classpath*:mybatisMapper/*.xml
  type-aliases-package: cn.com.nari.amp.entity
        
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  
sonar:
  ip: http://192.168.79.131:9000